### PR TITLE
Migrate enum renderer

### PR DESCRIPTION
**Pull request by mburri**
Migration of the Enum Renderer/ Control using the Picker component from react-spectrum.
This also fixes issue #20

### CODE REVIEW

**Comment by mburri** [comment]
there seems to be an open bug in react-spectrum that affects the rule example:
https://github.com/adobe/react-spectrum/issues/1213

**Review by hupf — CHANGES_REQUESTED** [review]
There is one more problem:

If you select the 'foo' option in the "Array" example, the "Bound data" reflects the change, but the option is not selected in the UI:

image

This works in the Material example:

image

**Comment by mburri** [comment]
> There is one more problem:
> 
> If you select the 'foo' option in the "Array" example, the "Bound data" reflects the change, but the option is not selected in the UI:
> 
> image
> 
> This works in the Material example:
> 
> image

The value is set correctly - you just cannot see it due to #28 

This will be resolved with #32

**Comment by hupf** [comment]
> The value is set correctly - you just cannot see it due to #28
> 
> This will be resolved with #32

Yes indeed :+1:

**Review by hupf — APPROVED** [review]

**Pull request merged**
