### PR TITLE
Improve color scheme selector

### PR DESCRIPTION
**Pull request by uudens**
Replace some custom elements in the Example files with React Spectrum elements in order to get color scheme selector working properly

Screenshot 2020-12-10 at 17 25 51-min
Screenshot 2020-12-10 at 17 18 21-min

### CODE REVIEW

**Comment by mburri** [comment]
Looks very nice! but there is an issue with the example picker that is out of sync with the shown example, if the theme changes.

How to reproduce:
- select an example, e.g. "numbers"
- switch theme

Behavior: the "numbers" example is still selected, but a different example is shown.

image

**Comment by uudens** [comment]
@mburri thank you for the feedback and for checking it out!
My bad, I've pushed a commit with a fix 🙂

**Comment by mburri** [comment]
On a closer look, I noticed that new code was not formatted with prettier and the license header was missing in the new file `theme.switcher.tsx` - I allowed myself to fix it. 

I think the prettier formatting is not documented and it would be a good idea to add a commit hook that asserts the prettier formatting - see #71 

@uudens feel free to merge this PR.

**Comment by uudens** [comment]
@mburri thanks!

**Pull request merged**
