### PR TITLE
Remove vanillaStyles & implement trim for spectrum controls #18

### PR DESCRIPTION
**Pull request by hupf**
Was ich gemacht habe:
- Die `vanillaStyles` komplett rausgenommen, inkl. `VanillaRendererProps` etc.
- Die Styles Redux Geschichte gelöscht.
- Die _trim_ Option für die Spectrum Controls/Cells via `width` umgesetzt. Das Trimming für die vanilla Controls/Cells drüfte also nicht mehr funktionieren, da wir die Klasse nicht mehr setzen.

So sieht es aus:

image

### CODE REVIEW

**Comment by reusr1** [comment]
@hupf seems a bit odd that the label is broken down in 2 rows, no?

**Comment by hupf** [comment]
> @hupf seems a bit odd that the label is broken down in 2 rows, no?

Good point. I'm not sure how the trim option should behave here. This is for example how the material adapter implements it:

image

The problem is, that in React Spectrum the text field and the label are contained in a single component (https://react-spectrum.adobe.com/react-spectrum/TextField.html#example). As far as I see, there is no way to control the field's size independently. We could sort of "hack" this via CSS... but I don't know if this is the way go.

**Review by mburri — COMMENTED** [review]
ok for me a soon as merge conflicts and failing tests are resolved.
thank you for showing me the ?? operator... didn't know about that one yet.

**Comment by hupf** [comment]
> @hupf seems a bit odd that the label is broken down in 2 rows, no?

@reusr1 I thought about this some more, my conclusions:

- It's the default behavior of the React Spectrum `TextField` to wrap the label (having no options/style props set at all). You can observe this in the example from the official documentation: https://react-spectrum.adobe.com/react-spectrum/TextField.html#example – the container and the label elements are just as wide as the input field; if the label gets longer, it simply wraps:

image

- If we do would override this behavior with CSS, we'd rely on React Spectrum internals and with that comes the risk of breaking when future React Spectrum releases change the internal structure. I'd strongly recommend to avoid this.

**Review by mburri — APPROVED** [review]

**Pull request merged**
