### PR TITLE
Feature/39 datepickers

### PR DESCRIPTION
**Pull request by mburri**
datepicker implementation for react-spectrum renderers.
as expected - they do not work as expected and have some glitches - since they are not even published yet.

additionally - travis ci is not able to install the dependencies from the tgz files - but I might probably miss something here.

### CODE REVIEW

**Comment by mburri** [comment]
It seems that it worked locally after I installed all dependencies manually in the correct order from the tarballs - once available, the packages could be resolved - but that does not work for a fresh clone.

**Comment by mburri** [comment]
The problem is, that we are hoisting the dependencies with lerna, but that does not work with file: specifiers as stated in the documentation...
also see this issue: https://github.com/lerna/lerna/issues/1679#issuecomment-461544321

**Comment by mburri** [comment]
I did some more tests locally and noticed that:
* everything works fine if I do the following:
```
rm package-lock.json
npm install
npm run init
```

but if I do 
```
npm ci 
npm run init
``` 
afterwards, the latter will fail - I also noticed that `npm run init` (which does a `lerna bootrap --hoist` modifies the package-lock.json that was created from the initial `npm install`

In fact - `lerna boostrap --hoist` itself runs npm install under the hood.

Adding --no-package-lock to the lerna boostrap command fixed the failing build - but this seems to be a workaround to make the local packages work.
I think we should not merge until the packages are available from npm

**Comment by reusr1** [comment]
@mburri we can still merge but may add a comment to the readme why we did it so we dont forget to revert it once the modules are released from react-spectrum

**Comment by hupf** [comment]
I don't like the approach to add the packages as tarballs to this repository. And also that we loose the ability to use the lock file.

I've therefore added the packages to a [separate repository](https://github.com/hupf/jsonforms-react-spectrum-dependencies) using [gitpkg](https://github.com/ramasilveyra/gitpkg) so we can reference them in the `package.json` and don't have to use the `--no-package-lock` flag. I suggest to move this registory repository under https://github.com/headwirecom/ if both of you agree with this solution.

Although the datepicker kind of works, the current state is pretty WIP – it does not look very good:

image

**Comment by hupf** [comment]
Well... it seems to make no difference – same problem as with tarballs. I had to ignore the lock file again to fix it.

The whole scenario of using unpublished packages in conjunction with Lerna seems to be problematic (apart from the fact that it's problematic anyway).

The question is whether we should really merge this in this state or not... and if yes, do we at least use the separate repository for the packages instead of the tarballs?

**Comment by reusr1** [comment]
switched this PR to draft as it is not ready yet

**Pull request closed without merging**
